# -------------------------------------------------------------------------------------
# Author Configuration | 作者配置
# -------------------------------------------------------------------------------------

name = "TRoYals"
email = "aozora00321@gmail.com"
link = "https://naglfar28.com"
